namespace FeishuNetSdk.Tests.Okr;

/// <summary>
/// 测试 更新 OKR 进展记录 请求体
/// <para>接口ID：7047052132604870684</para>
/// <para>文档地址：https://open.feishu.cn/document/server-docs/okr-v1/progress_record/update</para>
/// <para>JSON地址：https://open.feishu.cn/document_portal/v1/document/get_detail?fullPath=%2fuAjLw4CM%2fukTMukTMukTM%2freference%2fokr-v1%2fprogress_record%2fupdate</para>
/// </summary>
[TestClass]
public class Test_PutOkrV1ProgressRecordsByProgressIdBodyDto : TestBase
{
    [TestMethod]
    public void TestDto()
    {
        var json = """
{
    "content":{
        "blocks":[
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"粗体更新",
                                "style":{
                                    "bold":true
                                }
                            }
                        }
                    ]
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"*",
                                "style":{
                                    "bold":true
                                }
                            }
                        },
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"删除线更新",
                                "style":{
                                    "strikeThrough":true
                                }
                            }
                        }
                    ]
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"字体颜色更新",
                                "style":{
                                    "textColor":{
                                        "red":216,
                                        "green":57,
                                        "blue":49,
                                        "alpha":1
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"背景颜色验证",
                                "style":{
                                    "backColor":{
                                        "red":251,
                                        "green":191,
                                        "blue":188,
                                        "alpha":1
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"粗体+删除+字体颜色+背景颜色验证",
                                "style":{
                                    "bold":true,
                                    "strikeThrough":true,
                                    "backColor":{
                                        "red":251,
                                        "green":191,
                                        "blue":188,
                                        "alpha":1
                                    },
                                    "textColor":{
                                        "red":216,
                                        "green":57,
                                        "blue":49,
                                        "alpha":1
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"有序标题1验证，",
                                "style":{

                                }
                            }
                        },
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"粗体验证",
                                "style":{
                                    "bold":true
                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"number",
                            "indentLevel":1,
                            "number":1
                        }
                    }
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"有序标题2验证，",
                                "style":{

                                }
                            }
                        },
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"删除线验证",
                                "style":{
                                    "strikeThrough":true
                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"number",
                            "indentLevel":1,
                            "number":2
                        }
                    }
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"有序标题3验证，",
                                "style":{

                                }
                            }
                        },
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"字体背景颜色验证",
                                "style":{
                                    "backColor":{
                                        "red":251,
                                        "green":191,
                                        "blue":188,
                                        "alpha":1
                                    },
                                    "textColor":{
                                        "red":216,
                                        "green":57,
                                        "blue":49,
                                        "alpha":1
                                    }
                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"number",
                            "indentLevel":1,
                            "number":3
                        }
                    }
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"无序标题1验证，",
                                "style":{

                                }
                            }
                        },
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"粗体",
                                "style":{
                                    "bold":true
                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"bullet",
                            "indentLevel":1
                        }
                    }
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"无序标题2验证，",
                                "style":{

                                }
                            }
                        },
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"删除线",
                                "style":{
                                    "strikeThrough":true
                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"bullet",
                            "indentLevel":1
                        }
                    }
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"无序标题3验证，",
                                "style":{

                                }
                            }
                        },
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"字体背景颜色验证",
                                "style":{
                                    "backColor":{
                                        "red":251,
                                        "green":191,
                                        "blue":188,
                                        "alpha":1
                                    },
                                    "textColor":{
                                        "red":216,
                                        "green":57,
                                        "blue":49,
                                        "alpha":1
                                    }
                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"bullet",
                            "indentLevel":1
                        }
                    }
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"https://example/docx/doxcnO2Wkq0YPZQYLuJKyyOvLrh#doxcnSOui82swqk6c0o436Ak3nc",
                                "style":{
                                    "link":{
                                        "url":"https://example/docx/doxcnO2Wkq0YPZQYLuJKyyOvLrh#doxcnSOui82swqk6c0o436Ak3nc"
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            {
                "type":"gallery",
                "gallery":{
                    "imageList":[
                        {
                            "src":"https://internal-api-okr.feishu-boe.cn/stream/api/downloadFile/?file_token=boxbcofrHwpgexwxyvgasR2kgRh&ticket=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0YXJnZXRfaWQiOiI3MDQxNDMwMzc3NjQyMDgyMzIzIiwidGFyZ2V0X3R5cGUiOjMsImFjdGlvbiI6MiwiZmlsZV90b2tlbiI6ImJveGJjb2ZySHdwZ2V4d3h5dmdhc1Iya2dSaCIsInVzZXJfaWQiOiI2OTY5ODU1NTAxNzQ0ODM0MDkyIiwidGVuYW50X2lkIjoiNjg3NzUwMjY4NzYwOTQwNjk5MCIsImV4cCI6MTY0MDE1NjEyMX0.PSs94Z6ljo4e7U5cFV8dYW-bNDUOWdKXRK8B-XKruGCtKWrhsFLNKbNygUkOgHzbiPg65aSAiCaWyhh5YeX0aw",
                            "fileToken":"boxbcofrHwpgexwxyvgasR2kgRh",
                            "width":458,
                            "height":372
                        }
                    ]
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"任务列表未勾选验证",
                                "style":{

                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"checkBox",
                            "indentLevel":1
                        }
                    }
                }
            },
            {
                "type":"paragraph",
                "paragraph":{
                    "elements":[
                        {
                            "type":"textRun",
                            "textRun":{
                                "text":"任务列表已勾选验证",
                                "style":{

                                }
                            }
                        }
                    ],
                    "style":{
                        "list":{
                            "type":"checkedBox",
                            "indentLevel":1
                        }
                    }
                }
            }
        ]
    }
}
""";
        var result = Deserialize<FeishuNetSdk.Okr.PutOkrV1ProgressRecordsByProgressIdBodyDto>(json);
        Assert.IsNotNull(result);
    }
}